spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restauranttest_db
    username: postgres
    password: syspass

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none

server:
  port: 8080
